architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = project(":common").file("src/main/resources/${project.archives_name}.accesswidener")
}

repositories {
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    if (rootProject.architectury_loom_id == 'dev.architectury.loom-no-remap') {
        implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

        implementation "maven.modrinth:framinglib:1.0.0+1.16.5-Fabric"
    }
    else {
        modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

        modImplementation "maven.modrinth:framinglib:1.0.0+1.16.5-Fabric"
    }
}

if (rootProject.architectury_loom_id == 'dev.architectury.loom-no-remap') {
    configurations {
        shadowCommon
    }

    jar {
        archiveClassifier = "raw"
    }

    java {
        withSourcesJar()
    }

    shadowJar {
        dependsOn(jar)
        from(zipTree(jar.archiveFile))

        configurations = [project.configurations.shadowCommon]
        archiveClassifier = null
    }
}
